import { HeroHeader } from '@/components/header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function layout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<HeroHeader />
			{children}
		</>
	)
}
